/* TODO: this file must be generated by a sequence of tests. */

#define GSKB_ALIGNOF_POINTER_LOG2    2
#define GSKB_ALIGNOF_FLOAT_LOG2      2
#define GSKB_ALIGNOF_DOUBLE_LOG2     2
#define GSKB_ALIGNOF_UINT64_LOG2     2
#define GSKB_ALIGNOF_UINT32_LOG2     2
#define GSKB_ALIGNOF_UINT16_LOG2     1
#define GSKB_ALIGNOF_UINT8_LOG2      0
#define GSKB_ALIGNOF_STRUCT_LOG2     0

#define GSKB_BITFIELD_ENDIANNESS  G_BYTE_ORDER

#define GSKB_ALIGNOF_POINTER (1<<GSKB_ALIGNOF_POINTER_LOG2)
#define GSKB_ALIGNOF_FLOAT   (1<<GSKB_ALIGNOF_FLOAT_LOG2)
#define GSKB_ALIGNOF_DOUBLE  (1<<GSKB_ALIGNOF_DOUBLE_LOG2)
#define GSKB_ALIGNOF_UINT64  (1<<GSKB_ALIGNOF_UINT64_LOG2)
#define GSKB_ALIGNOF_UINT32  (1<<GSKB_ALIGNOF_UINT32_LOG2)
#define GSKB_ALIGNOF_UINT16  (1<<GSKB_ALIGNOF_UINT16_LOG2)
#define GSKB_ALIGNOF_UINT8   (1<<GSKB_ALIGNOF_UINT8_LOG2)
#define GSKB_ALIGNOF_STRUCT  (1<<GSKB_ALIGNOF_STRUCT_LOG2)

/* TODO: use compiler builtins where possible */
#define GSKB_ALIGNOF(type) \
  offsetof (struct { char a; type b; }, b)

#include "gskb-bitfield-macros.h"
#include "gskb-alignment.h"
#include "../gskghelpers.h"
