#! /bin/sh

set -x

gtkdocize || exit 1
libtoolize --automake || exit 1
aclocal$automake_program_suffix || exit 1
autoheader || exit 1
automake$automake_program_suffix -a || exit 1
autoconf || exit 1
