#! /bin/sh

case "$0" in
  */*) dir=`cd \`dirname "$0"\` && pwd` ;;
  *) dir=`dirname \`which "$0"\` ` ;;
esac
test -d "$dir" || {
  echo "Could not determine working directory for $0." 1>&2
  exit 1
}

new="$1"
base="$2"
class="$base"

methods="finalize"

while test x$class != x ; do
  case "$class" in
    GskStreamListener)
      class="GObject"
      ;;
    GskStream)
      methods="raw_read,raw_write,raw_read_buffer,raw_write_buffer,$methods"
      class="GskIO"
      ;;
    GskIO)
      methods="set_poll_read,set_poll_write,shutdown_read,shutdown_write,$methods"
      class="GObject"
      ;;
    *)
      class=""
  esac
done


"$dir/gsk-skeleton" --method="$methods" "$new" "$base"
